
- name: Disable SELinux
  selinux:
    state: disabled
  when: ansible_facts['os_family'] == "RedHat"

- name: Disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no
  when: ansible_facts['os_family'] == "RedHat"
