
- name: Install dependencies
  package:
    name: epel-release
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Install Netdata
  shell: |
    bash <(curl -Ss https://my-netdata.io/kickstart.sh) --dont-wait
  args:
    executable: /bin/bash
