
- name: Common configuration for all servers
  hosts: all
  become: yes
  roles:
    - common

- name: Install and configure Nginx on frontend
  hosts: frontend
  become: yes
  roles:
    - frontend

- name: Install Netdata on backend
  hosts: backend
  become: yes
  roles:
    - backend
